### ISSUE TITLE
LDAP authentication issue

### ISSUE THREAD

**Issue by tweeter** [pgina/pgina#171]
Hello Dev,

I have installed pGina on a Windows XP machine (LDAP client). I enabled the LDAP authentication plugin and configured the LDAP server settings. I tested the LDAP connection in pGina and it works. So here is the problem. I can login to the client machine using LDAP user. Then I did a password change for that user  from the LDAP server. But I couldn't login using that new password in the client.  The client machine keeps accepting the old password. I think it does not connect to LDAP server for checking the password. Is this a bug or an issue?

Kindly help.

**Comment by rajasimha1994** [comment]
hi, 
I have installed ldap server on Ubuntu 16.04. Trying to access windows 10  client to server by installing p Gina software in client machine. But it is showing "Failed to connect to LDAP server". Can you please give me any solution for this problem
