### ISSUE TITLE
Windows Server 2003: Service crash

### ISSUE THREAD

**Issue by AtosCompany** [pgina/pgina#181]
Hello,
We have the message below at least 20 times per day.
Pigina version installed is 3.1.7.1, with all the prerequisites on a Windows 2003 Server x86 Sp2 Ent.

7031,ERROR,Service Control Manager,Mon Feb 11 14:25:12 2013,No User,The pGina Service service terminated unexpectedly.  It has done this 1 time(s)

**Comment by nate-yocom** [comment]
Barring additional repro/info, closing.
