### ISSUE TITLE
silent install

### ISSUE THREAD

**Issue by zetan503** [pgina/pgina#240]
I would like a silent install feature for pGINA so that I can use chef to deploy it to newly built Windows servers. Additional configuration of the app would be helpful too.
 Any idea how to accomplish this?

Thanks

**Comment by daw42** [comment]
Yes, as of 3.2.x, we've switched to the NSIS installer.  If anyone is familiar with NSIS installer, I'd welcome a pull request that adds support for silent install.

**Comment by idealist1508** [comment]
It seems that ```pGina-3.2.4.1-setup.exe /S /D=C:\test``` is a correct call for a silent mode.
I miss only the log. :anguished:
