### ISSUE TITLE
Offline login

### ISSUE THREAD

**Issue by jerrychen68** [pgina/pgina#241]
When i using pGina with ldap plugin, i can't login if i can't connect to ldap server, how can i fix it?

**Comment by daw42** [comment]
Group issues can be tricky because there are a number of different settings that affect groups.  Take a look at the description under "local groups" here and perhaps it will help.  

http://pgina.org/docs/v3.1/local_machine.html

**Comment by nate-yocom** [comment]
Offline login for a user who has used the machine previously can be enabled by *not* scrambling passwords.

For a user who has never accessed a machine, this is not possible.
