### ISSUE TITLE
if it tries to open Excel on MAC, Word, and a PDF file, "It is locked for edit" 

### ISSUE THREAD

**Issue by tomvintage** [pgina/pgina#242]
Although OpenDirectory is built by MAC OSX 10.9.5 and I log in from Windows7 using pgina, After login, if it tries to open Excel on MAC, Word, and a PDF file, "It is locked for edit" will be displayed on nobody's being open. 

If there is a solution, please let me know. 

thanks.

**Comment by daw42** [comment]
This doesn't sound like a pGina issue, sorry.
