### ISSUE TITLE
pGina old login tile still in login screen after upgrading

### ISSUE THREAD

**Issue by pieterhouwen** [pgina/pgina#247]
Hi all,

I've recently updated pGina from 2.8 or something to 3.1.8.0 but the old login tile is still in the startscreen, this is also still the default tile, which causes confusion at my workplace.

How do I remove the old tile?

**Comment by nate-yocom** [comment]
I don't recall if we changed Cred guids or not, sounds like we did.  use the configuration ui to filter the old, or remove it from the registry.
