### ISSUE TITLE
pGina freezes when calling async method (in simulation)

### ISSUE THREAD

**Issue by wisien92** [pgina/pgina#248]
When i run code that's awaited the pGina during simulation freezes. 

Maybe I am doing unavailable thing ?

in my authenticate user funct:

 if (TestAsync.Test().GetAwaiter().GetResult() == 5)
     return new BooleanResult() { Success = true, Message = "Succes" };
 else
     return new BooleanResult() { Success = false, Message = "Failed" };

and my async funct looks like:

public static async Task<int> Test()
{
    await Task.Delay(2);
    return 5;
}

**Comment by nate-yocom** [comment]
Your sync waiting on an async task in the UI thread, where the async task wants to run.

dont use async/await
