### ISSUE TITLE
Option to hide the username/password fields in LogonUI before it connects to pGina service

### ISSUE THREAD

**Issue by swamp-fish** [pgina/pgina#250]
Here is a problem. MySQL Logger starts working after status is changed from Disconnected to Connected. But users can enter the system before this process and thus will make MySQL Logger Session mode useless.
Can you add an option to hide username/password fields before it connects?

At first i though this is https://github.com/pgina/pgina/issues/219 an option i am looking for. But there're no GUI settings to change that. In registry i've found keys such as HidePasswordField and HideUsernameField. I set those to "true" but it didn't do anything.

Windows XP SP3, Home.

**Comment by swamp-fish** [comment]
Ok, maybe atleast make "Login" button not functional and grey out until Service is connected. Pgina Configuration will have a checkbox for this option.

**Comment by nate-yocom** [comment]
How can/are users logging in before the services is connected?
