### ISSUE TITLE
pGina is unable to validate the server certificate, even if a valid CA root is installed as a trusted certificate.

### ISSUE THREAD

**Issue by ameneau-xetus** [pgina/pgina#251]
A trusted parent CA has been installed into the certificate store on the machine and the ldap server's web UI is accessible without displaying any certificate errors.

![screen shot 2015-04-25 at 2 42 14 pm](https://cloud.githubusercontent.com/assets/8021965/7335190/956b5624-eb62-11e4-9903-d1a70fa7a3bf.png)

However, the pGina ldap plugin is unable to validate the certificate.

Here's an excerpt from the simulation log:

> 2015-04-25 15:52:33,163 [1|DEBUG] LdapServer: VerifyCert(...)
> 2015-04-25 15:52:33,164 [1|DEBUG] LdapServer: Verifying certificate from host: freeipa.internal.xetus.com
> 2015-04-25 15:52:33,164 [1|DEBUG] LdapServer: Verifying server cert with Windows store.
> 2015-04-25 15:52:33,167 [1|ERROR] LdapServer: Server certificate validation failed: The X.509 certificate CN=freeipa.internal.xetus.com, O=INTERNAL.XETUS.COM is not in the trusted people store. The X.509 certificate CN=freeipa.internal.xetus.com, O=INTERNAL.XETUS.COM chain building failed. The certificate that was used has a trust chain that cannot be verified. Replace the certificate or change the certificateValidationMode. A certificate chain could not be built to a trusted root authority.
> 2015-04-25 15:52:33,168 [1|ERROR] LdapServer: LdapException: The LDAP server is unavailable.

**Comment by nate-yocom** [comment]
Did you place the CA cert in the trusted root of the *machine* (SYSTEM) account, or your own? Needs to be in the *machines* trusted root, or the trusted root store of whatever account runs the pGina Service.
