### ISSUE TITLE
pGina v3.1.8.0 LDAP Authentication of Synology NAS

### ISSUE THREAD

**Issue by Wotan4New** [pgina/pgina#252]
I have created an LDAP Directory on my NAS device and successfully bound pGina against it but the only password that seems to be accepted is the FQDN used when creating the database. Even when I know I'm typing in the correct password for the user pGina is reporting LDAP authentication error. pGina allows me to logon with any user-id using the administrative password.  Where am I going wrong!!  - any help gratefully received

**Comment by alanreeves** [comment]
Hi,
I use pGina with Ldap on a Synology Diskstation DS212J, Here are the pGina configuration parameters that work for me 

LDAP Hosts: Ip address of my NAS
LDAP port: 389
Group DN Pattern:                      cn=%g,cn=groups,dc=ldap,dc=e*******,dc=com
Member Attribute:                       memberUid:2.5.13.2:
Authentication User DN pattern: uid=%u,cn=users,dc=ldap,dc=e******,dc=com

Hope this helps you
REgards
Alan

**Comment by Wotan4New** [comment]
Cheers Alan, thanks for that. Works for me now. I should really read the documentation better!!
