### ISSUE TITLE
Unable to copy username and password to pGina login textboxes

### ISSUE THREAD

**Issue by maheshmadhyastha7** [pgina/pgina#254]
Hi,
I was trying to copy and paste the username and password from local computer notepad to the pGina username and password textboxes. However I am unable to do so, it wont allow to copy paste the credentials. Is there any way to allow copy pasting of user name and password in pGina.

Need help!

**Comment by maheshmadhyastha7** [comment]
Posted it long back, still no reponse.
Please help!!

**Comment by Wrightie** [comment]
:+1:
Same here... :(

**Comment by MutonUfoAI** [comment]
Thats not a bug
you can't do that using MS own Credential Provider!

I doesn't make sense in any way to support that.

**Comment by nate-yocom** [comment]
What @MutonUfoAI said.
