### ISSUE TITLE
Draw on login scren

### ISSUE THREAD

**Issue by Sopholos** [pgina/pgina#256]
This is not issue at all, but can' find any resources where I can find answer.
I need draw some image on login process. How can I do this in plugin?
There is no built-in methods to draw.
I was trying draw as usual - GetDC(0) and GetForegroundWindow + Graphics.FromHwnd but no luck.
Please kick me in the right way.

**Comment by MutonUfoAI** [comment]
> I need draw some image on login process.
be precise, during login or before login
during
https://github.com/MutonUfoAI/pgina/blob/master/pGina/src/CredentialProvider/Credential.cpp#L334
before
https://github.com/MutonUfoAI/pgina/blob/master/pGina/src/CredentialProvider/Credential.cpp#L572

**Comment by Sopholos** [comment]
When I already know user login. I think this is during or after...

**Comment by Sopholos** [comment]
pGina\src\CredentialProvider\Credential.cpp
void Credential::ProcessLoginAttempt(IQueryContinueWithStatus *pqcws)
