### ISSUE TITLE
Unable to login to Remote desktop on Windows 8 and 8.1 when logged in using PGina

### ISSUE THREAD

**Issue by km61053** [pgina/pgina#258]
It is observed that i am able to login to Remote desktop using normal user account and do all the basic/necessary actions.

Facing issues only with PGina user account.

**Comment by MutonUfoAI** [comment]
this report is not helpful
how is pgina configured
whats in the pgina log
http://pgina.org/docs/v3.1/index.html

**Comment by nate-yocom** [comment]
What @MutonUfoAI said.  Re-open with details.
