### ISSUE TITLE
pGina LDAP Single User Login Doesn't Work

### ISSUE THREAD

**Issue by xd1936** [pgina/pgina#259]
Hello!

We want to have a single user on the local machine that anyone can log into with their LDAP credentials. Right now, we have **LDAP: Authentication** and **Single User Login: Gateway** checked.

The simulation passes all tests and the logs look good, but when we go to login via the Windows 7 Login screen, it displays the logging in text for a moment... then quits back to the login screen.

This is pGina 3.1.8.0. Help!

**Comment by MutonUfoAI** [comment]
http://pgina.org/docs/v3.1/ldap.html
Typical Setup

**Comment by xd1936** [comment]
I found our issue. Single-user login doesn't work if the account you want to log into does not use a password!

**Comment by xd1936** [comment]
Should I re-file an issue that says "LDAP Single-user login doesn't work if the Windows account doesn't have a password"?

**Comment by nate-yocom** [comment]
See issue #283
