### ISSUE TITLE
Remote desktop crashes on using "another account"

### ISSUE THREAD

**Issue by maheshmadhyastha7** [pgina/pgina#264]
Hi,
I am using pGina 3.1.8.0 in our project. Whenever I try to take remote desktop, "Windows Security" dialog appears. It has two authentication options: "Use another account" and "pGina" (latter being active).However on entering the user name and password for another account the remote desktop is crashing. This works fine if I disable the if I  go to General configuration and "Disable" the "Credential Provider/GINA Status", the "Windows Security" dialogs suddenly all work just fine,

Please help how to fix this as this is a alarming issue in pGina.

**Comment by maheshmadhyastha7** [comment]
Can anyone respond,??

**Comment by MutonUfoAI** [comment]
try it with this one
https://github.com/MutonUfoAI/pgina/releases

uninstall pgina
delete pgina regkeys
than install the fork
and try

**Comment by maheshmadhyastha7** [comment]
Didnt work :(

**Comment by MutonUfoAI** [comment]
I have no problem to login automatically with a remote desktop
if the user exists already on the system

or login by (non autologon) RDC and typing username and password in the pgina login mask

i had to adjust the local machine plugin to add the user to the remote desktop users group

Explain your situation in detail and attach the pgina log (pastebin)
%ProgramFiles%\pGina\log\pGina.Service.ServiceHost_log.txt

**Comment by maheshmadhyastha7** [comment]
I want make it clear, I have no problem while logging into the remote machine with pGina configured. The issue is when we try to take RDP from that machine to other machine. On clicking "Use another account" the mstsc just crashes.

**Comment by maheshmadhyastha7** [comment]
All works fine if we 'Disable' the pGina from the pGina configuration tab. Looks like pGina is blocking the mstsc

**Comment by MutonUfoAI** [comment]
pgina is lacking NLA implementation
add this line to
C:\Users\%username%\Documents\Default.rdp
enablecredsspsupport:i:0
You can add this line into a saved rdp file too
A user than needs to login inside the rdp session

i also found this
https://groups.google.com/forum/#!topic/pgina-general/so2xvz_Oz_8

btw
if i use the def. windows provider ("use another account") i could login to my server

**Comment by maheshmadhyastha7** [comment]
I do not see that C:\Users\%username%\Documents\Default.rdp file. I am using windows server 2012 R2. I am not sure how you are able to use 'another account', everytime when I try to take the RDP from Windows server 2012 which has pGina configured, it crashes. I am able to take the RDP, when pGina is disabled in windows server 2012.

**Comment by MutonUfoAI** [comment]
C:\Users\%username%\Documents\Default.rdp
is a hidden file

just tested with server 2012 R2 and its the same as if win 7
If ive logged in as administrator pgina is working
If ive logged in as user member of group administrators pgina is *not working
If ive logged in as user member of group users pgina is *not working

*not working
the pgina credential provider is unable to connect to the pgina service
and the passwordProvider filter for CRED UI is not applied (its a subtype of credUI)
because of that the default password provider Credential provider is available.
If you still want to use pgina.fork to login to your server you'll getting an error message "error during login". If you use the def. windows password provider you are able to login

its a work arround not a solution

**Comment by maheshmadhyastha7** [comment]
Still I am having facing same issue. Is there any patch or something which can resolve this issue.
RDP crashes on using 'Use another account'.On disabling pGina RDP works.
Need help! Its bit urgent.

**Comment by maheshmadhyastha7** [comment]
You can also refer the issue mentioned here 
https://groups.google.com/forum/#!msg/pgina-general/tcQTtUjrRqE/otFGK2HgX1UJ


Need help urgently

**Comment by maheshmadhyastha7** [comment]
Can anyone respond? Its bit urgent

**Comment by MutonUfoAI** [comment]
you had 2 month to respond
you leave us in the dark about your setup
you dont deliver pgina or eventlog logs
im not able to reproduce your problem

Explorer crash upon "Use another account" for entering credentials to network share
unable to reproduce this either
just getting windows security dialog
passing username password
hit enter
and there we go

rdp session from win 7 to windows 2008R2
getting windows security dialog
choose "use another account"
passing username password
hit enter
and there we go
even saved credentials are working (user and admin)

the client and server are default setups

**Comment by maheshmadhyastha7** [comment]
Hi Hans, 
That was an example I shared. But the actual issue is, I login to Windows server 2012 which has pgina configured(This works). Now when I try to take rdp from this machine to other machine.,i will be prompted with option 1.pgina credential provider 2.use another account. Tried logging using pgina credential provider, but didn't work. So I tried taking rdp using 'use another account', now it crashed. Sorry for delayed response.

**Comment by maheshmadhyastha7** [comment]
Can you pls let me know where I can find the logs for pgina so that I can share the same with you.

**Comment by MutonUfoAI** [comment]
"you leave us in the dark about your setup" means
is this a domain server or member
a terminal server or ....
talk about your environment



MutonUfoAI  commented on Sep 28
.... (pastebin)
 %ProgramFiles%\pGina\log\pGina.Service.ServiceHost_log.txt

**Comment by maheshmadhyastha7** [comment]
It is VM hosted in VM workstation. It is not in domain. All are workgroup
users.

**Comment by MutonUfoAI** [comment]
reproduced with 3.1.8.0

no problem with
3.2.4.1 beta

upgrade and you are done

**Comment by maheshmadhyastha7** [comment]
Where I can get that version of pgina?

**Comment by MutonUfoAI** [comment]
https://github.com/pgina/pgina/releases

**Comment by maheshmadhyastha7** [comment]
Hi Hans,
Will try with this and update you with the result.

**Comment by maheshmadhyastha7** [comment]
Hi Hans,
I am not able to see the Service status on the logon UI after this version of pGina installation.
Is it removed in this version or am I missing any setting?

**Comment by maheshmadhyastha7** [comment]
Hi Hans,
Any update why its not showing service status on login UI?

**Comment by MutonUfoAI** [comment]
they changed it
username and password fields are hidden as long as the service is unavailable

**Comment by maheshmadhyastha7** [comment]
Hi Hans,
Looks okay now. However need to test a bit for the same.

**Comment by maheshmadhyastha7** [comment]
Thanks for ur reply and time.

**Comment by nate-yocom** [comment]
This was a null deref crash that is fixed in the beta.  workaround in prev versions is to type dummy values in the pgina portion of the mstsc CredUI prompt then use the actual provider to provide real values

**Comment by Johnson002** [comment]
no way with windows 10... we are using comtarsia now! works fine.
