### ISSUE TITLE
LDAP authentication help

### ISSUE THREAD

**Issue by r0perice** [pgina/pgina#267]
Hello everybody,

I have un virtual machine with some softwares installed and I want to grant access to this VM for my LDAP users. I need help to configure this !

My LDAP tree looks like :

- dc=my,dc=domain
  - groups
    - windows (with testing.ldap as memberUid)
  - people
    - testing.ldap

So, testing.ldap should be able to connect to the VM using is LDAP login/password. I configured pGina to do that but I have some problems. It's seems like pGina just use LDAP to create local users so when I delete my user from LDAP he still can log in the VM... Same problem if my user change is LDAP password he can't log in using is new password.

I really need help with that !

Regards,
Robin

**Comment by nate-yocom** [comment]
See beta for password change support (or the fork's current release http://mutonufoai.github.io/pgina/documentation/plugins/ldap.html#change_password) - likewise, see options for scrambling passwords on logout to prevent use of local user without ldap auth first.
