### ISSUE TITLE
Auto-select user login and auto-authenticate user

### ISSUE THREAD

**Issue by Sopholos** [pgina/pgina#272]
I need to develop hardware authentication.
User put card to reader and user associated with card automatically logged in.
As I understand plugins works only after user selects login and trying to enter something.
Please show me place in code where I can put auto-selecting user and auto-logon it.

**Comment by MutonUfoAI** [comment]
you should start with the SampleHardwareEventCredentialProvider example from MS first
soon you will realize there is no proper documentation ...

Credential Provider development is something for a masochist

**Comment by nate-yocom** [comment]
"Credential Provider development is something for a masochist" lol
