### ISSUE TITLE
Remote Desktop user login fails 

### ISSUE THREAD

**Issue by aoufou** [pgina/pgina#274]
Hello,
I have setup pgina 3.1.8.0 on windows 2012 r2. 
I am able to login with users that are part of freeipa3 (ldap)  on the console without problem.
I can login using RDP only if I have logged in through the console or by using the simulation.

If I try a user that exist on the ldap directory but didn't authenticate  yet using pgina simulation or local console I cannot login.

I have added remote desktop users in the localMachine plugin section Mandatory groups.

Any ideas thanks

**Comment by MutonUfoAI** [comment]
if you want to login using RDP the user need to exist on the system first

**Comment by nate-yocom** [comment]
Did you try disabling NLA on the RDP server?
