### ISSUE TITLE
I don't understand why connection with OpenLDAP is not possible

### ISSUE THREAD

**Issue by bellierjonathan** [pgina/pgina#275]
I try to use pgina with a OpenLDAP server and with groupOfUniqueName.

Can you help me to understand what's wrong with my configuration ?

pGina configuration:
http://postimg.org/image/crf7kspgb/

LDAP configuration:
http://postimg.org/image/tfwesl9k3/

Simulation on pGina:
http://postimg.org/image/hs2qc669f/

I try a connection with an account 'toto', but it's not working :/

Thanks,

**Comment by alanreeves** [comment]
Have  a look at issue #252. I had similar problems to you, but using Ldap on a Synology Diskstation. You need to modify the member attribute.
Regards, Alan Reeves

**Comment by bellierjonathan** [comment]
Thanks for your answer.
So, I tried to changed Member Attribute to 'uniqueMember'.

and it's not working.

**Comment by alanreeves** [comment]
You should change it specifically to "memberUid:2.5.13.2:" , as specified in issue #252. I don't know why you changed it to 'uniqueMember'. 
You must also change Group DN Pattern and Authentication User DN Pattern as described, but of course replacing your own value for "dc=e***"

**Comment by nate-yocom** [comment]
@bellierjonathan - see @alanreeves notes for fix
