### ISSUE TITLE
Prevent Multiuser Concurrency Issues with Active Session Warning?

### ISSUE THREAD

**Issue by basilosaurus** [pgina/pgina#280]
Hi all,

This was posted originally on your mailing list. I would like to see if this is any more active. Forgive me if I did not search thoroughly enough and link me to the topic that answers my question.

Now, I am looking to configure PGina so that upon user auth, as long as that user is still using that computer, it will prevent, or warn at the very least, users connecting via physical logins(sitting in front of the box) or connecting via RDP. This would mean that if a user locks the computer, the session would still be active under their name for a time.

Is there a feature that allows this now, or is this more of a feature request. Is this impossible? Would you guys recommend we move over to something different for multiuser auth to a single box?

Thanks.

**Comment by nate-yocom** [comment]
This isn't really in the domain pGina is meant to solve.
