### ISSUE TITLE
Unable to install pGina 3.2.4.1 silently

### ISSUE THREAD

**Issue by maheshmadhyastha7** [pgina/pgina#281]
Hi,
I am facing an issue while trying to install pGina 3.2.4.1 silently. I tried with /silent switch but it shows the installation pop up. Can anyone let me know how to install it silently.
Need help!!

**Comment by nate-yocom** [comment]
did you try:

pGina-3.2.4.1-setup.exe /S /D=C:\SomeDir

or similar?

**Comment by maheshmadhyastha7** [comment]
Worked like a charm!!! Thank you
