### ISSUE TITLE
pgina Windows users file read/write ownership on SAMBA file server

### ISSUE THREAD

**Issue by lkthomas** [pgina/pgina#284]
Is that possible to let pgina Windows users against LDAP would have proper permission set on SAMBA file server?

**Comment by nate-yocom** [comment]
I dont understand what/how pGina has anything to do with this... ?

**Comment by lkthomas** [comment]
pgina suppose to exchange user and group info with LDAP and write files with proper permission like in NFS.

**Comment by nate-yocom** [comment]
pGina does not write files, or have anything to do with file permissions aside from establishing the initial user account during sign in.
