### ISSUE TITLE
Notify plugin if tile was selected/deslected

### ISSUE THREAD

**Issue by mrfamazing** [pgina/pgina#290]
I'm trying to find a way to notify a plugin that it's tile has been selected or deselected in order to perform some logic. It doesn't seem to be built in functionality, is this something that could be done?

**Comment by mrfamazing** [comment]
Closing this, I determined there is no way to do this using pGina as it is. I ended up rolling my own message and sending it to the plugin once a tile was selected and deselected.

**Comment by nate-yocom** [comment]
Apologies for not getting back to you sooner - yes, you are correct - not built into pGina today, but adding a new message sent from the CP when selection/deselection happens would be the right approach.

Patches/pull requests welcome! :)

**Comment by mrfamazing** [comment]
Np, I have some very specific changes to my current branch, but I'll go ahead and create a pr for this.
