### ISSUE TITLE
Does pGna support any other hashing algorism for ldap authentication aside from MD5?

### ISSUE THREAD

**Issue by kaeoticEve** [pgina/pgina#383]
I find there are no option to set hashing algorism for ldap authentication, but it works for the accounts that uses MD5 for password hashing, if I change the hashing algorism to somethingelse in phpldapadmin, the pgina auth will not work.
----Edited 14/2/2022----
sorry for this issue, after some testing I found that only the sha512 that generated by the phpldapadmin is not supported

**Comment by JiewenGuan** [comment]
so
